import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
// import ManualHeader from "../components/ManualHeader";
import { useMoralis } from "react-moralis";

const supportedChains = ["4", "31337"];

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className="bg-gradient text-white px-5 h-screen">
      <Head>
        <title>Decentralized Lottery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <ManualHeader /> */}
      <Header />
      {isWeb3Enabled ? (
        <div>
          {supportedChains.includes(parseInt(chainId).toString()) ? (
            <div className="flex flex-row">
              <LotteryEntrance className="p-8" />
            </div>
          ) : (
            <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
          )}
        </div>
      ) : (
        <div>Please connect to a Wallet</div>
      )}
    </div>
  );
}
